version: '3.9'

services:
  backend:
    image: ghcr.io/blockscout/${DOCKER_REPO:-blockscout}:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-blockscout.env
    environment:
      - ETHEREUM_JSONRPC_HTTP_URL=https://evm-rpc.edge-devnet.babylonlabs.io
      - ETHEREUM_JSONRPC_TRACE_URL=https://evm-rpc.edge-devnet.babylonlabs.io
      - ETHEREUM_JSONRPC_FALLBACK_HTTP_URL=https://evm-rpc.edge-devnet.babylonlabs.io
      - ETHEREUM_JSONRPC_WS_URL=
      - ETHEREUM_JSONRPC_FALLBACK_WS_URL=
    volumes:
      - ./logs/:/app/logs/
      - ./dets/:/app/dets/
